model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"

general_settings:
  master_key: "or.environ/LITELLM_MASTER_KEY"
  ui_username: admin
  ui_password: "os.environ/UI_PASSWORD"
